### ISSUE TITLE
Add script to install with React

### ISSUE THREAD

**Issue by cdthomp1** [cdthomp1/mongo-express-node-template#11]
Add an installation script, `npx create-mern-app`, that installs the template as well as the main React template.

**Comment by meerhamzadev** [comment]
Can you explain this issue a bit more? Are we supposed to add a react project template created from npx create-react-app in this starter template?

**Comment by cdthomp1** [comment]
Sorry for the confusion, my thought process was to have the `npx create-mern-app` install the files from the Mongo Express Node template and just run the `npx create-react-app` as well. This script would set up two foloders called `server` and `client` with the Mongo Express Node template in the server folder and the files from `create-react-app` in the client folder. 

Hope this helps clarify any questions and please reach out if you have any more 😁

**Comment by meerhamzadev** [comment]
Oh, I get it now. That's great, I would like to contribute to that part. Can I?

**Comment by cdthomp1** [comment]
Absolutely!

**Comment by meerhamzadev** [comment]
Just a question/suggestion: Can I turn it into a CLI tool, and move the template files into a folder name node-mongo-template? And when we run the command create-mern-app it copies the files from the template folder to the server folder, and this CLI has a separate package.json with fewer dependencies (instead of merging CLI dependencies with template dependencies? ). Just like this It seems more logical

![image](https://user-images.githubusercontent.com/60890818/136445886-a310b222-3702-4b4f-8d71-a176b21e8ce2.png)

**Comment by cdthomp1** [comment]
Yes, that will make the base `npx create-men-template` work the same way
